-- =================================================================
-- IMPORT PRODUCTS AND ADD FIDGET ITEMS
-- Copy and paste this entire file into your Supabase Dashboard SQL Editor
-- Then click "Run" to apply the changes
-- =================================================================

-- Import existing products from CSV export
INSERT INTO public.products (
    id, title, description, price, is_customizable, category, colors, materials, sizes, 
    infill_options, personalization_options, images, video_url, is_active, likes_count,
    product_number, allowed_materials, allowed_sizes, estimated_grams_small, 
    estimated_grams_medium, estimated_grams_large, accessories_cost, color_slots,
    print_time_small, print_time_medium, print_time_large
) VALUES
(
    'a50903aa-2f35-4f9d-90ed-f011b5282888',
    'Geometric Planter1',
    'Modern geometric planter for succulents and small plants. Includes drainage hole.',
    22.00,
    false,
    'standard',
    '{}'::text[],
    '{}'::text[],
    '{}'::text[],
    '{}'::text[],
    NULL,
    '{}'::text[],
    NULL,
    true,
    0,
    '1215003',
    ARRAY['standard', 'premium'],
    ARRAY['small', 'medium', 'large'],
    60,
    110,
    180,
    0,
    '[]'::jsonb,
    60,
    120,
    180
),
(
    'ffa1006d-5f5b-4e35-a260-ea13efb4c3a6',
    'Custom Phone Stand',
    'Personalized phone stand with your name or custom text. Adjustable viewing angle.',
    18.00,
    true,
    'customizable',
    '{}'::text[],
    '{}'::text[],
    '{}'::text[],
    '{}'::text[],
    NULL,
    '{}'::text[],
    NULL,
    true,
    0,
    '1215002',
    ARRAY['standard', 'premium'],
    ARRAY['small', 'medium'],
    30,
    55,
    0,
    2.00,
    '[]'::jsonb,
    60,
    120,
    180
),
(
    '42f0da41-abe2-4b4b-9b6e-bbdf2a4fd778',
    'Articulated Octopus',
    'Flexible octopus toy with movable tentacles. Fun fidget toy for all ages.',
    15.00,
    false,
    'standard',
    '{}'::text[],
    '{}'::text[],
    '{}'::text[],
    '{}'::text[],
    NULL,
    '{}'::text[],
    NULL,
    true,
    0,
    '1215005',
    ARRAY['standard', 'premium'],
    ARRAY['small', 'medium'],
    35,
    70,
    0,
    0,
    '[]'::jsonb,
    60,
    120,
    180
),
(
    '2e3e52d1-e50e-4b77-a7d3-6a396b1a8795',
    'Name Plate',
    'Personalized desk name plate. Perfect for office or home office setup.',
    28.00,
    true,
    'customizable',
    '{}'::text[],
    '{}'::text[],
    '{}'::text[],
    '{}'::text[],
    NULL,
    '{}'::text[],
    NULL,
    true,
    0,
    '1215006',
    ARRAY['standard', 'premium'],
    ARRAY['medium', 'large'],
    0,
    65,
    120,
    0,
    '[]'::jsonb,
    60,
    120,
    180
),
(
    '8ea96e28-3b38-494f-b515-d39f82d2b788',
    'Dragon Figurine',
    'Detailed dragon sculpture with intricate scales and wings. Perfect desk decoration for fantasy lovers.',
    5.00,
    false,
    'standard',
    ARRAY['Bone White', 'Jade White', 'Light Gray', 'Pink', 'Purple', 'Black', 'Turquoise', 'Blue (Silk Multicolor)', 'Blue Hawaii', 'Gilded Rose', 'Glow Orange', 'Gold', 'Matte Ivory White', 'Matte Charcoal', 'Lavender Purple', 'Green (Silk Multicolor)', 'Matte Nardo Gray', 'Matte Mandarin Orange', 'Matte Terracotta', 'Midnight Blaze', 'Purple (Silk Multicolor)', 'Red (Silk Multicolor)'],
    '{}'::text[],
    '{}'::text[],
    '{}'::text[],
    NULL,
    '{}'::text[],
    NULL,
    true,
    0,
    '1215007',
    ARRAY['standard', 'premium'],
    ARRAY['small', 'medium', 'large'],
    50,
    85,
    150,
    0,
    '[]'::jsonb,
    60,
    120,
    180
),
(
    'd3166581-85db-4fd1-a0df-88e17a549129',
    'Custom Keychain Set',
    'Set of 3 custom keychains with your initials or logo. Great for gifts or business branding.',
    10.97,
    true,
    'customizable',
    ARRAY['Black', 'Turquoise', 'Blue (Silk Multicolor)', 'Green (Silk Multicolor)'],
    '{}'::text[],
    '{}'::text[],
    '{}'::text[],
    NULL,
    '{}'::text[],
    NULL,
    true,
    0,
    '1215008',
    ARRAY['standard', 'premium'],
    ARRAY['small', 'medium'],
    30,
    60,
    0,
    1.5,
    '[{"id":"background","label":"Background"},{"id":"foreground","label":"Foreground"}]'::jsonb,
    60,
    120,
    180
)
ON CONFLICT (id) DO UPDATE SET
    title = EXCLUDED.title,
    description = EXCLUDED.description,
    price = EXCLUDED.price,
    is_customizable = EXCLUDED.is_customizable,
    category = EXCLUDED.category,
    colors = EXCLUDED.colors,
    materials = EXCLUDED.materials,
    sizes = EXCLUDED.sizes,
    infill_options = EXCLUDED.infill_options,
    personalization_options = EXCLUDED.personalization_options,
    images = EXCLUDED.images,
    video_url = EXCLUDED.video_url,
    is_active = EXCLUDED.is_active,
    allowed_materials = EXCLUDED.allowed_materials,
    allowed_sizes = EXCLUDED.allowed_sizes,
    estimated_grams_small = EXCLUDED.estimated_grams_small,
    estimated_grams_medium = EXCLUDED.estimated_grams_medium,
    estimated_grams_large = EXCLUDED.estimated_grams_large,
    accessories_cost = EXCLUDED.accessories_cost,
    color_slots = EXCLUDED.color_slots,
    print_time_small = EXCLUDED.print_time_small,
    print_time_medium = EXCLUDED.print_time_medium,
    print_time_large = EXCLUDED.print_time_large;

-- Add new fidget products inspired by Etsy chainmail fidget
INSERT INTO public.products (
    title, description, price, is_customizable, category, colors, materials, sizes,
    infill_options, personalization_options, images, video_url, is_active, likes_count,
    allowed_materials, allowed_sizes, estimated_grams_small, estimated_grams_medium,
    estimated_grams_large, accessories_cost, color_slots, print_time_small,
    print_time_medium, print_time_large
) VALUES
(
    'Custom 3D Print Fabric Fidget Chainmail',
    'Flexible fabric-like 3D printed chainmail fidget toy. Perfect for stress relief, anxiety, and focus. Customizable colors and patterns. Smooth, flexible texture that flows like fabric.',
    24.99,
    true,
    'customizable',
    ARRAY['Black', 'Turquoise', 'Blue (Silk Multicolor)', 'Green (Silk Multicolor)', 'Purple (Silk Multicolor)', 'Red (Silk Multicolor)', 'Gold', 'Matte Charcoal', 'Matte Nardo Gray'],
    '{}'::text[],
    ARRAY['small', 'medium', 'large'],
    '{}'::text[],
    'Add custom text, initials, or choose from preset patterns',
    '{}'::text[],
    NULL,
    true,
    0,
    ARRAY['standard', 'premium'],
    ARRAY['small', 'medium', 'large'],
    45,
    90,
    150,
    3.00,
    '[{"id":"primary","label":"Primary Color"},{"id":"accent","label":"Accent Color"}]'::jsonb,
    90,
    180,
    270
),
(
    'Flexible Fidget Snake',
    'Long flexible snake fidget toy with articulated segments. Bend, twist, and manipulate for stress relief. Great for ADHD, anxiety, or just keeping hands busy.',
    19.99,
    false,
    'standard',
    ARRAY['Black', 'Turquoise', 'Pink', 'Purple', 'Gold', 'Matte Charcoal', 'Glow Orange'],
    '{}'::text[],
    ARRAY['small', 'medium'],
    '{}'::text[],
    NULL,
    '{}'::text[],
    NULL,
    true,
    0,
    ARRAY['standard', 'premium'],
    ARRAY['small', 'medium'],
    40,
    75,
    0,
    0,
    '[]'::jsonb,
    75,
    150,
    0
),
(
    'Fidget Cube Set',
    'Set of 6 mini fidget cubes with different textures and mechanisms on each side. Perfect for desks, pockets, or stress relief. Each cube has unique tactile features.',
    29.99,
    false,
    'standard',
    ARRAY['Black', 'Turquoise', 'Pink', 'Purple', 'Matte Charcoal', 'Gold', 'Blue (Silk Multicolor)'],
    '{}'::text[],
    ARRAY['small'],
    '{}'::text[],
    NULL,
    '{}'::text[],
    NULL,
    true,
    0,
    ARRAY['standard', 'premium'],
    ARRAY['small'],
    60,
    0,
    0,
    0,
    '[]'::jsonb,
    120,
    0,
    0
),
(
    'Flexible Lattice Fidget',
    'Geometric lattice pattern fidget toy that flexes and bends. Unique honeycomb design provides satisfying tactile feedback. Great for fidgeting during meetings or study sessions.',
    22.99,
    true,
    'customizable',
    ARRAY['Black', 'Turquoise', 'Pink', 'Purple', 'Matte Nardo Gray', 'Gold', 'Translucent Light Blue'],
    '{}'::text[],
    ARRAY['small', 'medium'],
    '{}'::text[],
    'Choose color combinations and add custom text',
    '{}'::text[],
    NULL,
    true,
    0,
    ARRAY['standard', 'premium'],
    ARRAY['small', 'medium'],
    50,
    100,
    0,
    2.50,
    '[{"id":"base","label":"Base Color"},{"id":"highlight","label":"Highlight Color"}]'::jsonb,
    90,
    180,
    0
),
(
    'Infinity Fidget Ring',
    'Smooth rotating infinity ring fidget toy. Wear as jewelry or use as a desk fidget. Elegant design that spins continuously for stress relief.',
    16.99,
    true,
    'customizable',
    ARRAY['Black', 'Gold', 'Matte Charcoal', 'Turquoise', 'Purple (Silk Multicolor)', 'Red (Silk Multicolor)'],
    '{}'::text[],
    ARRAY['small'],
    '{}'::text[],
    'Add initials or custom engraving',
    '{}'::text[],
    NULL,
    true,
    0,
    ARRAY['standard', 'premium'],
    ARRAY['small'],
    25,
    0,
    0,
    1.00,
    '[]'::jsonb,
    60,
    0,
    0
);

